server {
    listen 8000;
    server_name test.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name test.com;
    client_max_body_size 20M;
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;
    add_header Public-Key-Pins "pin-sha256='X3pGTSOuJeEVw989IJ/cEtXUEmy52zs1TZQrU06KUKg='; pin-sha256='MHJYVThihUrJcxW6wcqyOISTXIsInsdj3xK8QrZbHec='; pin-sha256='isi41AizREkLvvft0IRW4u3XMFR2Yg7bvrF7padyCJg='; includeSubdomains; max-age=2592000" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Xss-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;

    location /static/ {
        client_max_body_size 20M;
        autoindex off;
        alias /static/;
    }
    location /media/ {
        client_max_body_size 20M;
        alias /media/;
    }
    location / {
        client_max_body_size 20M;
        try_files $uri $uri/ @web;
    }
    location @web {
        client_max_body_size 20M;
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-forwarded-For $proxy_add_x_forwarded_for;
    }
}
